### ISSUE TITLE
Questions answer "Embed content" link hidden by tinymce editor

### ISSUE THREAD

**Issue by oseg** [iionly/extended_tinymce#3]
**Title**: Questions answer "Embed content" link hidden by tinymce editor

**Context**: When using "Questions" plugin v2.1 with "extended_tinymce" plugin v4.3.8 on elgg v1.12.11 with "embed" plugin activated

The issue is described here:
https://github.com/ColdTrick/questions/issues/7

**Comment by iionly** [comment]
Can you try if the problem also occurs with a slightly updated version of the Extended Tinymce plugin available in this branch https://github.com/iionly/extended_tinymce/tree/mentions-support ?

The changes are mainly for getting support of the mentions plugin included in extended_tinymce (still a work in progress but the extended_tinymce plugin will fully work without the mentions plugin). But during working on the mentions support I noticed an issue with padding of the editor area, so I've also made some changes in CSS. These changes might help with the menu link not getting hidded (I can't say if this also works with the questions plugin but you might give it a try).

**Comment by oseg** [comment]
I reproduce the issue with the extended_tinymce_mention_support branch.
To see the "embed content" link, I still have to add the "clear:right;" CSS property to the div.
Maybe adding this CSS property to the "mce-tinymce" class would fix the issue.

**Comment by oseg** [comment]
I also reproduce the issue independently of "questions" plugin: in the "utilities: maintenance mode" page, the "embed content" link is hidden by the tinymce editor.

**Comment by iionly** [comment]
Fixed in version 4.4.0.
