### ISSUE TITLE
FR: Make loaded plugins/toolbar configurable

### ISSUE THREAD

**Issue by dploeger** [iionly/extended_tinymce#7]
I recently wanted to add the "toc" plugin to tinymce (especially for the pages addon) and had to directly add this to your js-code. It would be nice if the admin could configure which plugins are loaded and how the toolbar is set up.

Thanks!

**Comment by iionly** [comment]
I had this idea already, too. But it's not trivial to make it configurable as menu entries depend on plugins and vice versa. So, there would be checks necessary to save only valid configurations. And I had no time so far to work on it. But I will keep it in mind.

**Comment by dploeger** [comment]
Would you really need the checks? I agree, that validating that is really hard as TinyMCE doesn't seem to offer some kind of validation call.

You could, however, offer the possibility with a note warning the administrator.

**Comment by iionly** [comment]
As I see it, with just offering just some input fields in plugin settings where you could enter the tinymce plugins to load and setting the toolbar items without any validations there's not much gained (if anything at all). Some plugins might require additional options in the tinymce editor init or even additional code (like css) and it would be nearly impossible to handle that sufficiently. In the end the admin most likely would have to edit the init function code directly anyway in most cases whereas the config made on the plugin settings page would slightly slow down the loading of the editor in any case. With the latest release of the extended_tinymce plugin I managed at least to simplify the plugin code. Now it's only one file where the editor is initialized and no longer two as before.

**Comment by dploeger** [comment]
Well, at least my issue with the toc plugin would've been fixed. 😁 

But, if you simplified the bootstrap code, it's now merely an override of a view, which is fine with me. Thanks!
