### ISSUE TITLE
When editing a page with lots of text, editing text with IE/Edge/iphone/ipad is very slow

### ISSUE THREAD

**Issue by oseg** [iionly/extended_tinymce#8]
Context: elgg v2.3.3 + extended_tinymce v4.7.1-2
Scenario:
- Create a page and paste a very big text
- Enter some text
=> Edition is very slow on Edge/internet explorer and also on iphone/ipad
=> The issue is NOT reproduced on Chrome/Firefox/Opera

**Comment by oseg** [comment]
I tried the [suggested workaround](https://stackoverflow.com/questions/39897420/typing-very-slow-in-tiny-mce-editor):
- In extended_tinymce_init.js, I removed the following code:
```
		setup : function(e) {
			e.on('change', function(e) { tinymce.triggerSave(); });
		}
```
and it fixed the issue. But I don't know if there are side effects in tinymce plugins...

**Comment by iionly** [comment]
I think removal of these lines is not an option. I had to add the tinymce save function for embedding with the bundled embed plugin to work.

I might have found a different way to fix it - at least not triggering the save function on the change event anymore. I need to do some further testing to see if it has any side-effects (also with other plugins). I'm afraid though that I can neither test on Windows (so no Edge/IE testing) nor with any Apple devices. So, I can only make a release when I think it works and you would have to test the new release on your own then.

**Comment by iionly** [comment]
Okay. Release 4.7.9 is out. Please test.

**Comment by oseg** [comment]
Thanks ! Your internal simplification in the code fixes the issue on IE & Edge, it is still not smooth on Iphone, but it is already better.
